name: refresh-url
on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '0 0 1 * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: refresh-url
        run: |
          bash ./scripts/url.sh
          mv -f ./url.txt ./data/
          echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT
      - name: commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: ${{ steps.last-commit.outputs.author }}
          commit_message: ${{ steps.last-commit.outputs.message }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
